import React from 'react';

const App = (props) => {
  const { notes } = props;

  return (
    <div>
      <h1>Notes</h1>
      <ul>
        {notes.map(note => 
        // React uses the key attributes of objects in an array to determine 
        // how to update the view generated by a component when the component 
        // is re-rendered.
          <li key={note.id}>
            {note.content}
          </li>
        )}
      </ul>
    </div>
  );
}

export default App;
